apiVersion: v1
kind: ConfigMap
metadata:
  name: cassandra-config
  namespace: data
data:
  ready-probe.sh: |
    #!/bin/bash
        if [[ $(nodetool status | grep $POD_IP) == *"UN"* ]]; then
          exit 0
        else
          exit 1
        fi